[manager]
cwd = { fg = "#f0dede" }

# Tab
tab_active = { fg = "#561d22", bg = "#ffb3b4", bold = true }
tab_inactive = { fg = "#ffdada", bg = "#3b080e" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ffb14a", bg = "#ffb14a" }
marker_cut = { fg = "#ffddb0", bg = "#ffddb0" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#e6c18d", bg = "#e6c18d" }

# Count
count_copied = { fg = "#281800", bg = "#ffddb0" }
count_cut = { fg = "#281800", bg = "#ffddb0" }
count_selected = { fg = "#561d22", bg = "#e6c18d" }

# Border
border_symbol = "│"
border_style  = { fg = "#ffb3b4" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#561d22", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#ffb3b4", fg = "#561d22", bold = true }
normal_alt  = { bg = "#524343", fg = "#d7c1c1" }

# Select mode
select_main = { bg = "#e6bdbd", fg = "#44292a", bold = true }
select_alt  = { bg = "#524343", fg = "#d7c1c1" }

# Unset mode
unset_main = { bg = "#e6c18d", fg = "#422c05", bold = true }
unset_alt  = { bg = "#524343", fg = "#d7c1c1" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#ffb3b4", bg = "#413737" }
progress_error = { fg = "#ffb4ab", bg = "#413737" }

# Permissions
permissions_t = { fg = "#bc4e4e" }
permissions_w = { fg = "#b37927" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff9b17" }
permissions_s = { fg = "#ff4141" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#ffb3b4" }
active = { fg = "#e6c18d", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb3b4" }
value = { fg = "#f0dede" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#ffb3b4", bg = "#561d22" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#ffb3b4" }
title = {}
hovered = { fg = "#ffddb0", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#413737" }
cand = { fg = "#ffb3b4" }
rest = { fg = "#561d22" }
desc = { fg = "#f0dede" }
separator = " ▶ "
separator_style = { fg = "#f0dede" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#f0dede" }
run = { fg = "#f0dede" }
footer = { fg = "#44292a", bg = "#e6bdbd" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#e6c18d" }
title_warn = { fg = "#ffb3b4" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#f0dede" },
    { name = "*/", fg = "#ffb3b4" },
]

# : ]]]
