[config]

[config.wallpaper]
command = "swww"
arguments = [ "img" ]
set = true

[templates.hyprland]
input_path = "./templates/hyprland.conf"
output_path = "~/.config/hypr/matugen.conf"

[templates.waybar]
input_path = "./templates/colors.css"
output_path = "~/.config/waybar/matugen.css"
post_hook = "pkill -SIGUSR2 waybar"

[templates.rofi]
input_path = "./templates/rofi.rasi"
output_path = "~/.config/rofi/config.rasi"

[templates.yazi]
input_path = "./templates/yazi.toml"
output_path = "~/.config/yazi/theme.toml"

[templates.ghostty]
input_path = "./templates/ghostty"
output_path = "~/.config/ghostty/themes/matugen"
post_hook = 'hyprctl dispatch sendshortcut "ctrl shift, comma, class:com.mitchellh.ghostty"'

# [templates.kitty]
# input_path = "./templates/kitty.conf"
# output_path = "~/.config/kitty/matugen.conf"
# post_hook = "pkill -SIGUSR1 kitty"

[templates.starship]
input_path = "./templates/starship.toml"
output_path = "~/.config/starship.toml"

[templates.qt5ct]
input_path = './templates/qtct.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = './templates/qtct.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'
