local map = vim.keymap.set
map("n", "<leader>w", "<c-w>", { desc = "Window" })
map({ "n", "v", "o" }, "<a-h>", "0", { desc = "Jump to Beginning of line" })
map({ "n", "v", "o" }, "<a-l>", "$", { desc = "Jump to End of Line" })
map({ "n", "v", "o" }, "<a-j>", "G", { desc = "Jump to Bottom" })
map({ "n", "v", "o" }, "<a-k>", "gg", { desc = "Jump to Top" })
map("n", "<esc>", vim.cmd.nohlsearch, { desc = "Hide Search Highlight" })
map("n", "<leader>x", function()
	vim.api.nvim_buf_delete(0, { force = true })
end, { desc = "Delete Buffer" })
